# Generated by Django 5.2.13 on 2026-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Anpress CMS', max_length=120)),
                ('site_description', models.CharField(blank=True, max_length=255)),
                ('active_theme', models.CharField(default='anpress-default', max_length=80)),
                ('posts_per_page', models.PositiveSmallIntegerField(default=6)),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configurações do site',
            },
        ),
    ]
