# Generated by Django 5.2.13 on 2026-04-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('featured_image', models.FileField(blank=True, null=True, upload_to='posts/', verbose_name='Imagem destacada')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='SEO: meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO: meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
